apiVersion: v1
kind: Service
metadata:
  name: web 
  labels:
    service: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - name: "http"
    port: 9292
    targetPort: 9292
    nodePort: 30080
