resources:
- name: container-demo
  type: git
  source:
    uri: https://github.com/eljuanchosf/container-demo.git
    branch: master

- name: container-demo-docker-image
  type: docker-image
  source:
    repository: ((dockerhub-id))/container-demo
    username: ((dockerhub-username))
    password: ((dockerhub-password))

jobs:
- name: build-docker-image
  plan:
    - get: container-demo
      trigger: true
    - put: container-demo-docker-image
      params:
        build: container-demo/
        tag_file: container-demo/.git/ref